package subway.domain;

import org.springframework.data.domain.Persistable;

import javax.persistence.*;

/**
 * create table station (
 * id bigint generated by default as identity,
 * name varchar(255) not null,
 * primary key (id)
 */
@Entity
public class Station implements Persistable<Long> {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;
    @Column(nullable = false)
    private String name;

    @ManyToOne
    private Line line;

    public Station() {

    }

    public Station(String name) {
        this(null, name);
    }

    public Station(final Long id, final String name) {
        this.id = id;
        this.name = name;
    }

    public void changeName(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public Line getLine() {
        return line;
    }

    // 연관관계 편의 메서드
    public void setLine(Line line) {
        this.line = line;
        if (!line.getStations().contains(this)) {
            line.getStations().add(this);
        }
    }

    public String getName() {
        return name;
    }

    @Override
    public boolean isNew() {
        return true;
    }
}
